### ISSUE TITLE
Cannot install DSpellCheck plugin from Notepad++ plugin manager

### ISSUE THREAD

**Issue by Eido95** [Predelnik/DSpellCheck#105]
When attempting to install **DSpellCheck** plugin (listed as version 1.3) from Notepad++ plugin manager, I get the following error:
> The specified module could not be found.
> 
> DSpellCheck.dll is not compatible with the current version of Notepad++.

The following details are versions of components relative to this error:
- Notepad++ version: v7.4.2 (32-bit)
- Notepad++ Plugin Manager version: 1.4.9.0
- Operation System version: Windows 10 Enterprise 64-bit

**Comment by Predelnik** [comment]
Sorry, this should be fixed in version 1.3.1 which I think is already available through plugin manager. Please check that.

(It may say something along the lines "Plugin could not be validated", and that's due to tiny mistake of mine, which I already fixed but it probably will take a while for plugin manager to catch on, anyway this warning could be ignored)

**Comment by Ben-Voris** [comment]
As you say, using Notepad++ v7.5.1 (32-bit), Plugin Manager 1.4.9.0 installed DSpellCheck Version 1.3.1.0 with a warning: "It is not possible to validate the integrity of 'DSpellCheck.dll'..." But it works.

**Comment by Predelnik** [comment]
Version 1.3.2 is on plugin manager for both x64, x86, so this should be fixed. Feel free to reopen if there's still a problem.
