### ISSUE TITLE
Can't download dictionaries, with DSpellCheck v1.3.1 and N++ v7.5.1, on my Win XP machine

### ISSUE THREAD

**Issue by guy038** [Predelnik/DSpellCheck#107]
**Context** :

Operating system : **Windows XP SP3**

Browser used : Mozilla **FireFox** ESR **v52.4.0** (**32** bytes)

N++ version used : **v7.5.1**

**Local** configuration, with the **doLocalConf.xml** file, on directory **C:\\_751**

Download of **DSpellCheck 1.3.1**, **without** the **Plugin Manager**. Directly from the link :

https://github.com/Predelnik/DSpellCheck/releases/download/v1.3.1/DSpellCheck_x86.zip

Installation of the library **DSpellCheck.dll**, by simple **extraction**, in the sub-directory **C:\\_751\Plugins**

**Issue** :

Once, N++ has started,

- A **first** click on **Plugins > DSpellcheck > Change Current Language > Download Languages...**

=> A **Unknown exception** window occurs !

- After a **second** click on **Plugins > DSpellcheck > Change Current Language > Download Languages...**

=> The **Download Dictionaries dialog** appears, **without** any dictionary name and with the top line **Status : Loading...**

- As **no** change occurs, any attempt of changing the **download server**, in the top drop-down list or clicking on the **Refresh** button, at bottom, leads to the following **exception** :

"An exception occurred. Notepad++ cannot recover and must be shut down. The exception details are as follows:
Code: 0xC0000005
Type: Access violation
Exception address: 0x01862EBC"

And :

"Do you want to save a dump^file?
Doing so can aid in developing Notepad++"

Then :

"Notepad++ will attempt tp save any unsaved data. However, dataloss is very likely"

And finally :

"Notepad++ was able to successfully recover some unsaved documents, or nothing to be saved could be found.
You can find the results at: 
D:\DOCUME\~1\xvr823\~1.380\locals\~1\Temp\N++RECOV"

On the other hand, if, after starting N++, you click, first, on **Plugins > DSpellcheck > Settings...** then, on the **Download dictionaries...** button, it causes the **same exception** , as above !

Is that issue, possibly related to my **Win XP** OS ?

Thanks for your i**nvestigations** !

guy038

**Comment by Predelnik** [comment]
I've checked it on WinXP and it happens me too, I will try to investigate.
By the way looks like I can't download/update any plugins through plugin manager on XP, is it known problem?

**Comment by Predelnik** [comment]
Luckily enough this problem is happened to be known on the internet and manageable. Here's new version for you to check.
https://drive.google.com/uc?export=download&id=0B_fsSThBdq2mTS1XNDJQcTYyTkk

Short description of the  problem and solution:
As it happens one can't use Thread Local Storage (TLS) in dynamically loaded DLLs on windows xp
https://support.microsoft.com/en-us/help/118816/prb-calling-loadlibrary-to-load-a-dll-that-has-static-tls
TLS is used by default by static variables since I believe "magic statics" C++11 feature.
http://en.cppreference.com/w/cpp/compiler_support
There are some static variables used in new concurrency code I used + in FTP code I use, so just switching to newer compiler enabled usage of TLS.
Luckily it can be disabled with `/Zc:threadSafeInit-` compile switch. I will add it in 1.3.2 version.

PS I think in the future I will make x86 version to be WinXP friendly version with appropriate toolset and  `/Zc:threadSafeInit-` and x64 version with better non-xp toolset and thread safe initialization enabled. x64 winxp could be provided on demand in rare cases.

**Comment by guy038** [comment]
Ah ! Many **thanks** for your **quick** reply, **Sergey** !

I confirm that your **new** version is working quite **fine**, on my **Win XP SP3** configuration and I could **download** my favourite **dictionaries** : *English GB, English US, French, French 1990* and *French Classique* :-))

In my **previous** post, I just forgot **two** points :

- On an other directory, I have a **local** version of N++ **v7.4.2** , with DSpellCheck **v1.2.14.2** installed. It's working **nice** too, **without** any trouble !

- As soon as the **Hunspell** directory, of DSpellCheck **v1.2.14.2**, containing the **dictionaries**, is, simply, **duplicated** in the **C:\\_751\\Plugins\\Config** folder, the **last** DSpellCheck **v1.3.1** worked, as usual !

Best Regards,

guy038

**Comment by Predelnik** [comment]
Version 1.3.2 is on plugin manager, so downloading dictionaries should work fine on Windows XP. Feel free to reopen if there's still a problem.
