### ISSUE TITLE
VS Resource Editor fails to open DSpellCheck.rc

### ISSUE THREAD

**Issue by SinghRajenM** [Predelnik/DSpellCheck#119]
I'm using Cmake 3.10.1 and VS 2017. After creating VS solution, I'm not able to open resource view. Below error occurs.

![image](https://user-images.githubusercontent.com/14791461/34469027-c595386c-ef3b-11e7-9a77-5c330d5f25e4.png)

So my question is:
1. Is there any reason for not using Visual studio solution instead of creating it from CMAKE?
2. Everytime, we need to create new solution whenever makefile is changed (this is always true for a person who has less knowledge of makefiles).
3. We need to create two separate projects for x86 and x64.
4. So can't we get rid of all these and create VS solution (.vcxproj, .vcxproj.filters and .sln)?

**Comment by Predelnik** [comment]
Originally I used CMake to support different Visual Studio versions, now it's less of the need. However I just recently used CMake to generate compile database and it's not an easy thing to do with just Visual Studio projects. The other reason is compiling with clang-cl, it perhaps doesn't work super well but allows use of some sanitizers, maybe compiling with MinGW works or could be made to work too. The other reason is I have wildcards everywhere in CMake because I'm super lazy and Visual Studio has very poor support for wildcards at the moment.

So personally I don't see much benefit in going back to VS project. And by the way what does error in resource view has to do with it? I checked and it could be worked around with `APSTUDIO_HIDDEN_SYMBOLS` hacks but it's probably easier just to use ResEdit to be honest.

**Comment by SinghRajenM** [comment]
> And by the way what does error in resource view has to do with it?

VS resource view should be able to open rc file straight forward. Neither file "DSpellCheck.rc" is opened in resource editor nor as plain text (when click view code). Though able to compile successfully. 
![image](https://user-images.githubusercontent.com/14791461/34470004-be144606-ef4e-11e7-9a39-c43d433ed367.png)


> ```APSTUDIO_HIDDEN_SYMBOLS``` hacks

I tired to do that, but could not succeed. However earlier version prior to 1.3.3 (If I remember correctly), there was no such error and no hacks were needed.
> it's probably easier just to use ResEdit to be honest

IMHO, when we already have builtin rich editor why do we need an additional program to do the same task.

**Comment by Predelnik** [comment]
> I tired to do that, but could not succeed. However earlier version prior to 1.3.3 (If I remember correctly), there was no such error and no hacks were needed.

Ok I will commit required changes a bit later because I succeeded in doing that. But still it doesn't explain what CMake has to do with it. 1.3.3 was using CMake as well as many versions before. Possibly the reason is unicode conversion. But in the end it's just one more problem of built-in Resource Editor.

**Comment by Predelnik** [comment]
Should work now in master.

**Comment by SinghRajenM** [comment]
Closing
