### ISSUE TITLE
v1.4.0 - does not spell check text in HTML files

### ISSUE THREAD

**Issue by ballios** [Predelnik/DSpellCheck#128]
v1.4.0 (stable) does NOT spell check at all - Russian, English.
I use Hunspell library (as always, many years) but only in v1.4.0 I have such big problem of spell check totally inactive.
Sergey, please fix this issue as fast as you can.
I am completely discouraged...

**Comment by Predelnik** [comment]
Can you describe your problem in more detail please, for example starting with which system you use, what kind of Notepad++ installation do you have, etc. Because quite obviously it works for me.

**Comment by ballios** [comment]
I have:
- Win 10 (last updates) x64
- Notepad++ 7.5.4 (x32)

I already wrote to you that v1.3.5 - is working normally.
After I updated via Plugin Manager (as always) on v1.4.0 - this DSpellCheck problem appeared.

**Comment by Predelnik** [comment]
How does the problem manifest itself? Nothing is underlined? Does find next/ find prev. misspelling menu items work? Is there any dictionaries in `Plugins->Change Current Language`
Can you also show me the contents of the file `%appdata%/Notepad++/plugins/config/DSpellCheck.ini`?
If Hunspell doesn't work can you check if native speller does work (since it should be usable on windows 10)?
![image](https://user-images.githubusercontent.com/2133957/36242298-1c67cd4a-122c-11e8-99a4-f5e7e70c8e06.png)

**Comment by ballios** [comment]
I understood the problem.

v1.4.0 - does NOT check at all (neither Russian, nor English) in all files with the extension * .html
But it checks correctly (Russian, English) only in files with the extension * .txt

There is no such problem in v1.3.5.

In Notepad - I have (as always) files and * .html and * .txt

Please fix this for v1.4.0

P.S. Win 10 spell check is not acceptable due to its extreme slow down in Notepad!

**Comment by Predelnik** [comment]
Thanks! I changed the code determining which parts of text should be checked for various languages in this release and messed up this part for HTML a bit. I will probably make a proper release with fix this weekend. (also will double check this for some other mostly-text languages like tex)

Here's version where I hopefully fixed this for html:
https://drive.google.com/uc?export=download&id=1eGya-P3lcjGrPfWFeDC8lOlx3suKJPIi
It would be great if you make sure that it works for you.

> P.S. Win 10 spell check is not acceptable due to its extreme slow down in Notepad!

Yeah it's the slowest one currently due to being non-native, but dictionaries are not that bad. And there is possibly some ways to speed-up still left. But anyway I was recommending it not as a permanent switch but only as a check that this is not a problem only with Hunspell but now I see that it's not.

**Comment by ballios** [comment]
Thanks a lot!
I will wait for the official release with impatience!

**Comment by Predelnik** [comment]
I've created 1.4.1 with this fix
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.1
It will be updated on plugin manager in a while.

**Comment by ballios** [comment]
I don't know why v1.4.1 is not visible in plugin manager?
Still v1.4.0 only....

**Comment by Predelnik** [comment]
Yes it takes a while for it to update, it may take a week or so.

**Comment by Predelnik** [comment]
1.4.1 now is available on 32 and 64-bit plugin managers, so I'm closing this for now. Feel free to reopen if you still have issues.
