### ISSUE TITLE
How spell check own UDL with delimiters same as .txt file and Normal text file rules

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Predelnik/DSpellCheck#132]
When I have `.txt` file and select `Normal text file` in left bottom corner then plugin works fine, all wrong words are highlighted. But for `.txt` I made my own UDL rules (named Doc) where set only 4 delimiters and their style and thats all.  I use this delimiters to make some title/header more readable for my instructions, sth like this:
@@@@ Title 1 @@@@
==== Title 2 ====
After this plugin check only words in that delimiters. Is there any way force plugin to check all words in document, the same as `.txt` and  `Normal text file` definition does?

**Comment by Predelnik** [comment]
Yes I think always spell-checking "Default style" for UDL is correct. I will fix this in 1.4.3.

**Comment by Predelnik** [comment]
Oh no. Actually it's not as easy as I initially thought. For UDL which describe some programming language like UDL for shader syntax default style goes to variable/function names:
![image](https://user-images.githubusercontent.com/2133957/37507042-c794438c-28fd-11e8-99a5-e57beeb08c57.png)
And it seems to be correct to not check them by default. On the other hand you can create UDL for language which is mostly text like in your case and then it makes sense to spell-check default style always.

I can of course make spell-checking default UDL style based on the following checkbox:

![image](https://user-images.githubusercontent.com/2133957/37507111-1d6d5d52-28fe-11e8-8798-1c6686549729.png)
But then you will have spell-checking for variables turned on in other languages which may not be desirable.

The less damaging option for now seems to be to add separate check-box for checking/not checking UDL default style. It would harm only users which use several UDLs some of which are text-based and some programming language based.

And the most flexible option is to support specifying list of UDLs for which to check default style. Though it looks like N++ doesn't tell name of UDL currently selected in plugin interface.

**Comment by ArkadiuszMichalski** [comment]
You can even add specifying list of files with regex rules (same as in `File Types (Separate with semicolon ( ; ) )`) for which default styles always apply. Thanks to this, we can, for example, check all .js files according to the rules of Javascript, but for a specific file like `description.js` use default styles . Well, but the filtration by the name UDL would also be a good solution.

**Comment by Predelnik** [comment]
For now I've decided to settle with single checkbox which is turned on by default (so text will be spell-checked).

I don't really want to limit it to extension because extensions are already mentioned inside UDL specification and it will require duplicating of that list, which seems unnecessary.

Limiting it to UDL names on the other hand currently seems unfeasable because they are not exposed by Notepad++ API so it would probably require doing pull-requests to N++. Maybe I will get down to it some time in the future.

**Comment by RubiLobster** [comment]
I too use a custom UDL and enjoyed your addon until only commented/string text could be spell checked as I wrote. For now I rolled back my version to 1.3.5 but was curious if there's an intermediate version I can use between the two that does not have this limitation.

Thanks in advance!

**Comment by Predelnik** [comment]
@RubiLobster 
Sorry but I don't completely understand you, this issue was about __less__ things being spell-checked in UDL since 1.3.5. In 1.4.3 I added check box to switch between the old behavior and the one I made in 1.4.x which by default is enabled so spell-checking UDL in 1.4.3 should be exactly the same as in 1.3.5. If you want behavior from 1.4.0-1.4.2 you should just uncheck this check box:

![image](https://user-images.githubusercontent.com/2133957/38715104-f486327a-3ee1-11e8-8a19-fa0eefa7f957.png)

**Comment by RubiLobster** [comment]
No worries. Here's the paradigm which led to your confusion...

1. I had an issue with DSpellCheck not indicating spelling mistakes one day.
2. Noticed that NotePad++ Plug In Manager was pushing out 1.4.1 (FYI - it still is)
3. Located this topic and read you had a solution in mind which concluded with a statement about some future version
4. So I wrote the post above, not realizing it was fixed in 1.4.3 (see #2)

Until your fast reply yesterday, thank you again by the way, there was no indication that the problem described in this topic was fixed by a new checkbox in 1.4.3. Now I know to ignore the plug-in manager in NotePad++ (see #2) and just install 1.4.3 from: https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.3

**Comment by Predelnik** [comment]
Yeah thanks, that's a bit unfortunate that 32-bit plugin manager's plugin list gets approved very slowly for some reason. I usually close bugs after version becomes available on both(32 & 64 bit) plugin managers, thus I didn't close this one yet for example.

**Comment by Predelnik** [comment]
Seems like 1.4.3 is available for x86 plugin manager, thus closing this issue
