### ISSUE TITLE
DSpellCheck not working with v7.5.9 of Notepad++

### ISSUE THREAD

**Issue by noonand** [Predelnik/DSpellCheck#156]
My install of NP++ will not spell check any document despite being installed (just took the latest version from this site and copied it in)

I've uninstalled all plugins and NPP itself but to no avail and am really looking for suggestions here to get this working. The toolbar button has lit up and the "Spell Check Automatically" is checked.

Debug log:

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppExport.dll DSpellCheck.dll JSLintNpp.dll JSMinNPP.dll NPPJSONViewer.dll NppTextFX.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll Tidy2.dll XMLTools.dll

**Comment by Predelnik** [comment]
So it worked with previous versions but stopped with 7.5.9, maybe it just because the plugin version was old (1.3.something) before?
Do you use any non-standard options?
Is there any languages available in plugins->DSpellCheck->Settings Language combo box?
Can you post contents of the file %appdata%/notepad++/plugins/config/DSpellCheck.ini if possible?

**Comment by noonand** [comment]
I thought that it might be the age of the plugin so I went to the site yesterday and pulled the latest version. I manually installed that then and restarted NPP. 
Re using any non-standard options, quite possibly yes. I've cycled through most combinations at this stage while trying to get it working. I've attached the INI file here but will deleting it set things back to the default?

[DSpellCheck.ini.txt](https://github.com/Predelnik/DSpellCheck/files/2580265/DSpellCheck.ini.txt)

There is no corresponding INI file under the Program Files (x86) folder

Thank you for your time and attention in this matter. Please let me know if there's anything you need such as a dump of the NPP process or otherwise.

**Comment by Predelnik** [comment]
So in your attached .ini file only single option is non-default, so I don't think that the problem is there. And yes deleting it will reset everything to default.

Sadly dump of the process won't be much of a help if there's no crash.

One thing you can try is switching library in the setting to "Native (Windows)" and checking if it works. It's not a complete solution of course because you may still may prefer to use default Hunspell but with it we may rule out the possibility of something being wrong with dictionary files.

The other thing is - you can check that "c:\Program Files (x86)\Notepad++\plugins\Config\Hunspell\" contains valid english dictionary files.

**Comment by noonand** [comment]
Just an update; deleting everything DSpell related (both under  %userprofile% and Program Files (x86) folders) has fixed this issue. I then ran NPP as Admin and pulled down some dictionaries, which got written to the  C:\Program Files (x86)\Notepad++\plugins\Config\Hunspell folder and I've got spelling working again. Appreciate your time and help on this!

**Comment by Predelnik** [comment]
Thank you for reporting that it is fixed now!
It would be still nice to know the cause of the original issue but if it's not reproducible even from your side now, probably it will have to stay unresolved for now.

**Comment by noonand** [comment]
Again, thanks for the time you put into this and if there's anything further I can do to help, just let me know...

**Comment by IsaacABrown** [comment]
I ran into this issue as well and it appears something broke in the Hunspell install which did cause the language selection drop down to not have any options. Changing to Windows Native fixed it for me, but I'll probably reinstall to get Hunspell working again or take a look at Aspell.

**Comment by Predelnik** [comment]
Sorry this is probably due to issue #172 which was fixed in version [1.4.12](https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.12)
As a workaround turning spell-checking on should make language list have options.

**Comment by JoeVoelkel** [comment]
Same problem here, but here was an easy fix for me. (I am using 32-bit v7.8.5):

click plugins/DSpellCheck/Settings, then (after I found out that C:\Users\myUserName\AppData\Roaming\Notepad++\plugins\Config\Hunspell did not even exist), click on Download and install your language(s).

That's it!
