### ISSUE TITLE
Any plans to upgrade Spell Check

### ISSUE THREAD

**Issue by MurraySobol** [Predelnik/DSpellCheck#158]
![image](https://user-images.githubusercontent.com/40715947/48640946-3baf7e80-e9a6-11e8-9263-c0b821326af4.png)

Any plans on upgrading to use new Windows 10 Spell Check API?
It was introduced in Windows 8.1.
I realize that this would be a problem for user running older versions of Windows.

**Comment by MadokaAyukawa** [comment]
I have a "Native (Windows)" option under Library dropbox in the settings. Is that what you are looking for?

**Comment by Predelnik** [comment]
Yes Native (Windows) option in "Library" combo box uses Windows 8 spell check API. It's not a complete replacement for Hunspell and has some performance problems that's why it is not used by default.

By my personal experience - dictionaries provided by Windows seem to be better, suggestion mechanism on the other hand works very poorly, probably even worse than Aspell.

**Comment by Predelnik** [comment]
I'm closing this since it seems to be already implemented. Please comment if you have any problem still.
