### ISSUE TITLE
Vector <T> too long

### ISSUE THREAD

**Issue by DavidDuffy** [Predelnik/DSpellCheck#169]
Whenever i collapse an XML document with DSSpellcheck enabled i get this error in a popup.
The title of the popup is "PluginsManager::runPluginCommandException"
The message of the popup is "vector <T> too long"
As soon as this issue arises, any scrolling horizontally produces another popup, and occasionally more than one, which also occasionally hide behind the notepad++ window so i cant see they're there until i minimise or close n++.
Any ideas?
Im using: 
version 1.4.6.0 of DSSpellCheck
version 7.5.9 of Notepad++.

**Comment by Predelnik** [comment]
Thank you very much for reporting!
First of all it looks like similar issue was fixed in version 1.4.7:
https://github.com/Predelnik/DSpellCheck/blob/master/Changes.md
So please try the newest version:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.10
If this issue still exists on the newest version it would be great if you can send me xml file where it is triggered.

**Comment by DavidDuffy** [comment]
You're a star. Notepad++ was telling me it was up to date at v1.4.6
Updating now. Thank you.
