### ISSUE TITLE
Plugin breaks scrolling

### ISSUE THREAD

**Issue by joeyhub** [Predelnik/DSpellCheck#17]
This plugin breaks scrolling in notepad++ using a mouse wheel. It will scroll left but nothing else.

**Comment by Predelnik** [comment]
This bug is very niche one imo. I do think it was possibly happening with "Suggestion Button" suggestions style which was creating window that possibly may have been stealing focus. Now suggestions are done through context menu. So I think I'll close this. Feel free to comment if there is still an issue.
