### ISSUE TITLE
DSpellCheck does not check new text

### ISSUE THREAD

**Issue by lucatrv** [Predelnik/DSpellCheck#208]
I have Notepad++ v7.8.5 on Windows 7, but this has been happening for a while already (maybe for about 1 year or more, while previously I did not have this issue).

Although I keep "Spell Check Document Automatically" enabled, when I write new text it is not checked. To check all text I need to disable and then re-enable it. When I open a file all text is spell checked.

I have configured multiple languages for DSpellCheck (English USA and Italian), but I do not think this affects the issue because it happens no matter which language I select.

**Comment by Predelnik** [comment]
Hello, sorry for late reply. If it won't be hard can you check if it depends on the version of the plugin, for example you may check quite old versions like [1.3.5](https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.5)

The whole list of available versions is here:
https://github.com/Predelnik/DSpellCheck/releases

I have not encountered that problem before but it might be that somehow timer is not working correctly since spell-checking is timer based. Also can you share your settings file from `%appdata%/Notepad++/plugins/config/DSpellCheck.ini` if it won't be hard. Also removing this file reset settings to default which might also provide help in some cases (but plz post here its contents before trying that :) )

**Comment by lucatrv** [comment]
I have version 1.4.6.0 installed (I guess it's the one coming with Notepad++ v7.8.5).
Here is my `%APPDATA%\Roaming\Notepad++\plugins\config\DSpellCheck.ini` file content:

```ini
[SpellCheck]
Hunspell_Multiple_Languages=en_US|it_IT
Hunspell_Language=<MULTIPLE>
```

I don't see anything strange...

**Comment by Predelnik** [comment]
Oh wait it's pretty obvious then , sorry I somehow forgot about it. Due to changes which happen in Notepad++ 7.7 you need to update plugin at least to the version 1.4.13. Unfortunately it was the time when basically interface between plugin and N++ changed and it's out of my control.
So the picture is the following:

* DSpellCheck before 1.4.13 works with Notepad++ before version 7.7 only.
* DSpellCheck with version 1.4.13+ works with Notepad++ 7.7+.

I would recommend to update it to newest version which is [1.4.15](https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.15)

**Comment by lucatrv** [comment]
I now updated it and... it works, thanks!! Sorry but I thought that new plugin versions were automatically delivered with each Notepad++ updates. If this is not the case, do I always need to check for new plugin updates manually?...

**Comment by Predelnik** [comment]
There is a `plugins admin` item in Notepad++ plugins menu which lets you found relevant updates and download them faster but as far as I can tell it doesn't support auto-updating currently. I can only help that it would be improved to include it.

Previous plugin system delivery (namely `Plugin Manager` plugin) had that feature, so there was a bit of regression in that department unfortunately.

**Comment by lucatrv** [comment]
OK thanks, maybe that's why I never had this kind of issues before. However since DSpellCheck is installed by default by Notepad++, I would have expected with each Notepad++ update to also get an updated version of DSpellCheck (if not the latest one, at least one compatible with the updated version of Notepad++).
See notepad-plus-plus/notepad-plus-plus#8084

**Comment by Predelnik** [comment]
Unfortunately it _was_ installed by default and now it's no longer true, but I understand that the current situation is far from the best, my only hope is that plugin admin will finally receive auto-update function at some point.
