### ISSUE TITLE
No longer offers dropdown of correction words

### ISSUE THREAD

**Issue by Itzak613** [Predelnik/DSpellCheck#221]
Misspelled words are highlighted, but suddenly can't access the dropdown of suggested corrections to select one.  When clicking on a misspelled word nothing happens and if the Special Button is enabled it just disappears on click with no dropdown. 

If I click on the option to Show Suggestions at Curser,  it works one time then never again unless I go back and reselect the option to get one more suggestion,  it does not stay enabled.

dspellcheck ver 1.3.16.0
notepad ++ ver 7.8.9
Windows 10 x64 with all updates

**Comment by Predelnik** [comment]
Hello!
Do you mean version 1.4.16? Can you list other plugins you're using and also post contents of DSpellCheck.ini from `%appdata%\Notepad++\plugins\config`? Also has it stopped working after installing an updated version of the DSpellCheck?

**Comment by Predelnik** [comment]
Seems like issue with Special Button could be reproduced on my side, so maybe it has something the version of N++. Context menu called with right click or hotkey seems to work for me though

**Comment by Uhf7** [comment]
@Predelnik 

Thank you for your feedback, I just checked it out. 

> I just had a bit of trouble with my N++ plugin after the following PR: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8475

There is indeed a new `SCN_UPDATEUI/SC_UPDATE_H_SCROLL` notification, which arrives in the moment when the Suggestions button is clicked, as result of Notepad++ PR 8475.

I will create another PR like this:

CURRENT:

	case WM_ACTIVATE:
	{
		_pEditView->getFocus();
		auto x = _pEditView->execute(SCI_GETXOFFSET);
		_pEditView->execute(SCI_SETXOFFSET, x);
		x = _pNonEditView->execute(SCI_GETXOFFSET);
		_pNonEditView->execute(SCI_SETXOFFSET, x);
		return TRUE;
	}

NEW:

	case WM_ACTIVATE:
	{
		if (wParam != WA_INACTIVE)
		{
			_pEditView->getFocus();
			auto x = _pEditView->execute(SCI_GETXOFFSET);
			_pEditView->execute(SCI_SETXOFFSET, x);
			x = _pNonEditView->execute(SCI_GETXOFFSET);
			_pNonEditView->execute(SCI_SETXOFFSET, x);
		}
		return TRUE;
	}

With this modification, DSpellCheck works without the workaround. But, since the current code is already released in 7.8.9,  you might to have to keep it anyway. Sorry for that. I included the lines there, because there was already a `_pEditView->getFocus();` call, which is actually useless too while deactivating the window.

> maybe WM_ACTIVATEAPP was a better option for such an update ...

I cannot put it into `WM_ACTIVATEAPP`, it doesn't work there.

> .. if only alt-tabbing is of interest

The problem occurred on minimize/restore and while restoring the session after starting Notepad++.

**Comment by Predelnik** [comment]
@Uhf7 Thank you very much for reply and a fix! I actually was hesitating to ask for a fix because the best solution was to avoid deactivating N++ window on my side (with `WM_MOUSEACTIVATE` and so on) but I couldn't achieve that after trying for a while for some reason, luckily the workaround ended up not being too bad so that's not a huge deal after all.

**Comment by Itzak613** [comment]
The 1.4.18 release (x64) has resolved this issue for me.
