### ISSUE TITLE
FR: Ignore words that start or end with # (hashtag aka pound sign)

### ISSUE THREAD

**Issue by Gitoffthelawn** [Predelnik/DSpellCheck#247]
Currently DSpellCheck has an option to ignore words that start or end with a single quote (` ' `).

Can another similar option be added for hashtags (#)?

Ideally, I'd love to see something even more flexible like three input fields within the settings:

   1. Ignore words that start with:
   2. Ignore words that end with:
   3. Ignore words that start and end with:

**Comment by Predelnik** [comment]
I do think instead of adding such customization detail it might be easier to have an option to ignore any regex (or the opposite) option for advanced users, it might require better regex engine than standard C++ though due to it's notorious slowness, I will try to look into that. Also I think #248 could be solved using the same feature.

**Comment by Predelnik** [comment]
I have added ignore words via regexp in version [1.4.21](https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.21), hope it should cover most of the cases suggested. As an example for starting or ending with #:
![image](https://user-images.githubusercontent.com/2133957/122806467-06443d80-d2d3-11eb-84b2-ed25eaa8d914.png)

**Comment by Gitoffthelawn** [comment]
Thank you!  See https://github.com/Predelnik/DSpellCheck/issues/248 for feedback from initial testing.

**Comment by Predelnik** [comment]
Should be mostly solved with ignore regexp feature
