### ISSUE TITLE
No spelling errors found

### ISSUE THREAD

**Issue by hfrmobile** [Predelnik/DSpellCheck#322]
Even the Plug-in is installed and enabled, it does not find any typos e.g. This is asdsadfasfa a test!
It looks like that it doesn't work when using NP++ with Dark-Mode theme...

**Comment by Predelnik** [comment]
![image](https://github.com/Predelnik/DSpellCheck/assets/2133957/15012094-5127-4c9c-a176-f1e69bd5461e)
Works fine in dark mode for me.
Do you have any languages in `Plugins->DSpellCheck->Change Current Language`?

**Comment by roy-tate** [comment]
This problem occurs when a user does not select a current language (perhaps only when no languages are downloaded).

I had this issue with DSpellCheck 1.5.0 and Notepad++ 8.6.

When I selected "Find Next Misspelling", it did nothing.
Once I selected "Change Current Language", it offered only the choice "Download Language" (something like that).

Once I downloaded "English (United States)", it worked fine.

I think when we click "Find Next Misspelling", if no Current Language is configured, it should prompt us or otherwise indicate an error.
