### ISSUE TITLE
'analog' isn't a word in the dictionary

### ISSUE THREAD

**Issue by TGit-Tech** [Predelnik/DSpellCheck#50]
Suggest adding the word 'analog' to the dictionary.

**Comment by Predelnik** [comment]
Even though this bug is quite old, still I would like to point out that bugs related to dictionaries are not related to plugin itself.
https://github.com/Predelnik/DSpellCheck/wiki/Bug-Reporting#bugs-related-to-dictionaries

Additionaly I checked for the word `analog` and it is present United States English dictionary and in Great Britain English it's spelled as `analogue`. That is correct as far as I can tell.

Closing bug for reasons listed above.
