### ISSUE TITLE
Major design flaw

### ISSUE THREAD

**Issue by Predelnik** [Predelnik/DSpellCheck#53]
The big flaw the plugin has is that a lot of interaction of GUI is done through sending messages to windows from worker thread. All of it (especially after correcting exiting procedure) may lead to potential dead-lock on Npp's exit. It needs to be fixed asap.

**Comment by Predelnik** [comment]
Ok, now it has ultra-high priority.

**Comment by Predelnik** [comment]
In current master branch I've separated GUI work for Settings/ RemoveDictionaries and LanguageList to be done in main thread and I guess it's already decreases chance of possible hang in the end tremendously, now I need to do the same thing for network / DownloadDictionaries and look for rest of SendMessage stuff, some, which are not easily removable should be done with timeout and handled carefully.

**Comment by xeonx1** [comment]
@Predelnik 
With the latest release (1.2.14.2) notepad++ process still fails to exit when due to dspellcheck. What's the status for fixing this? Any ETA for releasing an update with this fix?
Implementing this could allow dspellcheck to become a suggested plugin again for notepad++, which its stability (primarily with this issue it seems to me) has prevented.

**Comment by xeonx1** [comment]
@Predelnik @edwpang
Predelnik, please approve pull request #77 to issue, with fix from edwpang which may fix this hang on close issue, and at least fixes crash on settings and some on close issues for x64.

**Comment by Predelnik** [comment]
Is it something which happens only with x64 version? Seemingly it never hangs for me on exit, but just has some potential to do so.

I don't mind approving pull request, putting out new version will be a bit more bothersome though.

**Comment by edwpang** [comment]
Yes, it only happens on 64 bit. The pointers get truncated to 32 bit on
64bit, I changed to DWORD_PTR, it should work for both 32 bit and 64 bit.

**Comment by xeonx1** [comment]
I have only tested with Windows 10 64-bit (though Notepad++ itself appears to only be available as a 32-bit build), and the issue often occurs for me.
@edwpang Is your fix (from #77 ) supposed to also fix the issue with Notepad++ process never exiting, especially after the window was closed via Alt-F4 (though not every time, and possibly occurring in other cases as well)?
@Predelnik 
Its a pretty major issue, bad enough to make me look for alternatives for Notepad++. I often end up with as many as a dozen notepad++.exe processes which never exit, even days later, and have to go and check what processes are running after every time I close Notepad++ and then manually terminate them in order to avoid that.
Per #427 and other posts I've seen and the fact that DSpellcheck has been auto-disabled by Notepad++ due to stability issues, it seems many others may also be encountering this and related issues. 
 Considering that, it would be a big help if a build could be published resolving this. Hopefully this fix is enough to get DSpellcheck no longer auto-disabled if that is still the case.

**Comment by xeonx1** [comment]
@Predelnik
Can you please release an updated build so don't end up so everyone with x64 so don't keep getting leftover notepad++ much of the time when closing the window?

**Comment by xeonx1** [comment]
@Predelnik and @edwpang 
Is this something you can release a build for soon?  If not, does someone else have access to release such builds, or if not, can you grant someone it, or can someone release an unofficial build with this fix?
Again today I noticed I have 15 different Notepad++.exe processes running in the background for days, despite no windows being visible, due to the bug with this plugin, even though it appears that the latest commit provides a fix for this issue.

**Comment by Predelnik** [comment]
I've built a version with this change, byt don't think that it's gonna change much for your situation though.
https://dl.dropbox.com/s/b55lfif9rnzivre/DSpellCheck.zip

**Comment by xeonx1** [comment]
@Predelnik 
Thanks for providing that build. 
That release seems to have fixed the issue entirely. No more leftover Notepad++.exe processes, regardless of how I close the window (Alt-F4, etc.)!
I suggest making the release available to everyone (including auto-update with Notepad++ plugin manager).

After that, you can see if the Notepad++ maintainer can remove the blacklisting of it DSpellCheck (the auto disabling of the plugin on install/update of Notepad++), since this seems to fix the major remaining issue (on exiting) that was cited as the reason for its blacklisting, as I recall.

@edwpang Thanks for implementing that fix.

**Comment by edwpang** [comment]
@Dan,
I am pleasantly surprised it fixed the issue for x86. I originally though
my fix only applied for x64. Thank you for letting me know.



Regards,
Edward

**Comment by xeonx1** [comment]
I actually have Windows 10 x64, for which I was reporting the issues. I don't have any 32-bit OS to test with. That said, its the standard 32-bit Notepad++ installation, as I'm not aware of any 64-bit build being available.

**Comment by xeonx1** [comment]
@Predelnik 

Can you make an official release (for use Notepad++ updater and GitHub releases) of the following build you have linked to earlier, for others to benefit from it as well?
https://dl.dropbox.com/s/b55lfif9rnzivre/DSpellCheck.zip

As mentioned, after testing it, it seems to have fixed the critical issue with dozens of leftover notepad++ processes for 64-bit OS users, and may be enough to get DSpellCheck to be considered stable instead of blacklisted.
Thanks again for providing that build.
