### ISSUE TITLE
Comparing INI files

### ISSUE THREAD

**Issue by pl71** [Predelnik/DSpellCheck#54]
INI files are extensively used for translations. It would be nice to compare INI files, only by checking equal keys.

**Comment by Predelnik** [comment]
So I'm not sure what the original bug was about but I changed spell-checking ini files in the following way:
Keys and section names will be checked as identifiers, e.g. when this checkbox is ticked off:
![image](https://user-images.githubusercontent.com/2133957/37253039-450ec536-253d-11e8-8733-5423a37d3558.png)
Values will be checked always, since I think they are either numbers or string this should make sense most of the time.

**Comment by Predelnik** [comment]
Closing this, some fixes were done bue I'm not sure that it fixed original bug, feel free to reopen and/or comment.
