### ISSUE TITLE
Request of New Features

### ISSUE THREAD

**Issue by DmFedorov** [Predelnik/DSpellCheck#63]
The neu feature in context menu of Settings v.1.2.14 is very good!! 
Now I can "Copy All Misspelled Words in Current Document to Clipboard". 
It is very usefull for making .dic files.

---

I need 4 features that will make plugin (not .dic-file): 
1)  Keys combination to add the Misspelled Word in User dictionary and to Ignore it.
(The button and context menu - good, but Keys better and much faster) 

2) User permanent Ignore list (in User dictionary or somewhere else, and if possible using regular expressions). 
Now I can add words to ignore, but I can not save this list and then fix it. This list is so far available only for the session. 

3) Separate checking Misspelled Words (first for example English and then Russian). In other words: I want to ignore e.g. only English words until I will want to test English separate.

4) Is it possible to mark strings with Misspelled Words e.g. mark them with Npp bookmarks from plugin? 

---

I did a full translation  of your plugin on the Russian language (By the way the plugin code is very complicated: creating a Russian DSpellCheck.dll lasts 20 times longer than a notepad ++ .exe)
http://rghost.net/7dsglMwyd

**Comment by Predelnik** [comment]
Ok first about "Copy All Misspelled Words in Current Document" I added it as a 'hidden feature' for one specific user, looks like it's not so hidden then, lol.

1) This could be done but a lot of default keys are taken, I guess I would have to assign it to some very weird keys initially then.
2) I guess it could be done, however if it's just a list of words then I don't see much difference from user dictionary itself. Regular expressions is another matter though, maybe ignoring words based on regular expression is useful however I have to think in which way would be best to implement it.
3) If I understand this correctly, the question is how to differ between misspelled words in one language from the other. For Russian and English it's easy but for language using latin letters it's literaly impossible. I need better understanding how to handle it.
4) Can't say for sure, looks like they can be marked with something else than bookmark, however don't see much point it since you can jump between misspelled words already.

So about localization - Thanks for doing it, that was a lot of word I guess. About the right way to localize plugins though: I actually looked into it way back and looks like Notepad++ itself doesn't have much support for plugin localization. If it at least would return which localization is currently selected in N++ I guess plugin localization could be done. I could've asked for this feature I guess but since I'm myself not much of a localizaiton user I didn't do it.

So - about plugin development in general: There's a certainly a lot of features could be done (even the ones that I myself would like to see) including yours but lately I lack time and motivation to implement even moderately complex features. The other holding factor is that my views on coding on C++ has changed so much since I started so now I think that plugin's code is horrible and I need to refactor most of it but that would require even more time to do so (even for a little part) and that repulses me.

However there is a good news, looks like for newer versions of N++ I finally can use modern versions of Visual C++ which wasn't possible a year ago, this makes refactoring a lot easier and fun. However still need to gather some time and motivation at least to start. 

So as usual can't promise anything I guess :(

**Comment by DmFedorov** [comment]
-----1) This could be done but a lot of default keys are taken, I guess I would have to assign it to some very weird keys initially then.----
You can not assign hot keys at all. I need only the commands that will be visible in the mapper of  Notepad++.  I have no such commands, there is only a context menu. I see it, but cannot assign.

----2) I guess it could be done, however if it's just a list of words then I don't see much difference from user dictionary itself. ..-----
Why do not you see the difference?
With the help of a custom User dictionary can I fill up the words that are written correctly. 
Ignore list is the senseless words. They underline the words. I want to ignore them, but in no case does not wish that this nonsense was offered to me as a correct spelling.
If I will have a regular expressions I can describe words to ignore completely.

-----3) If I understand this correctly,----
I think you have understood correctly. The solution is simple. Make only possible. For example, for Russian user: excluded from scanning all words containing a) the Latin or b) Russian letters.
If the user is a Frenchman for him, you can disable scanning of all words containing specific French characters. If it is a German - disable checking of words with umlauts.

----4) Can't say for sure, looks like they can be marked with something else than bookmark, however don't see much point it since you can jump between misspelled words already.----
Why bookmarks? Because Npp can cut, copy, delete, invert line with bookmarks, and the same goes for lines that do not have bookmarks.

---So about localization----
You don't need think about any localization for your plugin. The one who wants to make it simply uses special tools to do this. E.g. old free Restоrаtоr. If you want to alleviate potentially possible translation, you can in yours dll have not only Dialog-section, But even one Strings-section.  In this section must be all 78 lines that I translated from section Hаrdсоded Wizes strings.

There is another possibility: you allow connection translantion-dll. You don't need to make it. I will make it in 2 minutes from yours Dll. It will be 10 times less and contain an exact copy of the external interface and the section Strings without kode. Then I will translate it and will not depend from version of your plugin.
Thank you for your plugin.
