### ISSUE TITLE
Ignore Words options not working reliably for "All Letters Capital" and "Having not First Captial Letter"

### ISSUE THREAD

**Issue by dbolton** [Predelnik/DSpellCheck#74]
**Steps to reproduce**
1. Create a new text file with the following sample text: `mISPELING MISPELING mispeling`
2. From the main menu choose "Plugins > DSpellCheck > Settings..."
3. Click on the "Advanced" tab
4. Insure you are starting with a checkmark next to "Having not First Capital Letter" and "All Letters Capital"
5. Then remove the checkmark next to "All Letters Capital" and click "Apply"

**Expected behavior**
The second sample word ("MISPELING") should have an underline.

**Actual behavior**
The second sample word is not underlined. 

**Workaround**: (continue with steps 7 and 8)
6. Remove the checkmark next to "Having not First Capital Letter" and click "Apply" (all three sample words are underlined as expected)
7. Add the checkmark next to "All Letters Capital" and click "Apply" (first and third sample words are underlined as expected)

**Comment by Predelnik** [comment]
Ok so the problem here is that these ignore groups are not actually non-interesting and even more than that one group contains the other group ("Having non first letter capital" contains "All letter capital"). However I agree that you may wish to disable weird words with capital letters in random places while spell checking abbreviations, so I think I will fix that.

**Comment by Predelnik** [comment]
I splitted ignore groups as described in comment above. Fix should be available in version 1.4.0.
