### ISSUE TITLE
DSpellCheck spelling ColdFusion saves as Coldfusion with bad case

### ISSUE THREAD

**Issue by einst3** [Predelnik/DSpellCheck#89]
computer config: w7x64 latest sp, npp7.3.2-7.4.1-x86, dspellcheck 1.2.14.2.
note: npp appdata installed plugins
en_US.usr saves ColdFusion as Coldfusion with bad case. happens to all languages. any word that has camel case in it saves as word lowercase except first letter.

dspellcheck.ini...
[SpellCheck]
Hunspell_Multiple_Languages=en_GB|en_US|fr_FR|la|es_NEW
Hunspell_Language=en_US
Suggestions_Number=9

**Comment by Ben-Voris** [comment]
This looks like [hunspell issue 458 ](https://github.com/hunspell/hunspell/issues/468).

**Comment by einst3** [comment]
issue stays open till [hunspell issue 468](https://github.com/hunspell/hunspell/issues/468) is resolved

**Comment by Predelnik** [comment]
Well I don't think it's fully related to hunspell issue because plugin performs word tokenization by itself, so I can implement tokenization by camel case as an option without Hunspell supporting it internally. However that's an improvement which is yet to be implemeneted.

Btw I've recently checked popular spell-checker plugin for vscode which does this kind of tokenization and as a bonus checks variable/function names because of it. So I think this feature is promising and I hope I'll implement it in near future.

**Comment by Ben-Voris** [comment]
Is it necessary to split the words and spell check them separately? "iTunes" is an example where this would fail. I want a lower-case "i" to be rejected by the spell checker. And, it should be possible to reject any other capitalization (e.g., iTUNES, ITUNES, etc.). 

I can't think of a way to handle this short of adding the exact capitalization of a camel-case word to the dictionary and to check it as such.

**Comment by Predelnik** [comment]
It certainly not easy to make things perfect in all cases. Splitting CamelCase words is the most simple way for now. Most of spell-checkers today are case-sensitive thus to support your scenario I would have to try if any way of word capitalization is correct (2^n variants), I could however introduce the option which will convert all the words to lower case before asking spell-checker but then you would have to add words like `itunes`, `nasa` to user dictionary yourself, because default dictionary would have them capitalized properly.

**Comment by Predelnik** [comment]
Camel case splitting of words in 1.4.0 which is available through plugin manager. I also noticed that originally this issue was about adding word in non-traditional case to dictionary, I checked it and in 1.4.0 it works fine to me (see picture below). If you still have this issue with 1.4.0 feel free to reopen the issue or open a new one.
![image](https://user-images.githubusercontent.com/2133957/36394851-37cc68b8-15c7-11e8-84fa-bc75b93f4f36.png)
