### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by donho** [Predelnik/DSpellCheck#93]
Hi @Predelnik , hope you're well.
Sorry for asking question via issues, but the question is kind of urgent.

I would like to know a behaviour: if DSpellCheck.dll is in plugin directory and it's loaded afer the start of Notepad++, and there's no `DSpellCheck.ini` but there are 3 dictionaries (let's say US, UK and French) installed in Hunspell directory. which dictionary DSpellCheck will use? Is there any policy (order) to choose the dictionary?

**Comment by Predelnik** [comment]
Currently it tries to set en_GB (UK dictionary) if it's found, otherwise it's first in the list alphabetically.

**Comment by donho** [comment]
Thank you for your answer @Predelnik 
FYI, I'm planning to include DSpellCheck back into distribution (unless if you have any objection).
`DSpellCheck.dll` and 2 US dictionary files aff & dic will be add ino installer and zip, 7z files for both x86 and 64 packages.

Have I missed somethings?

**Comment by Predelnik** [comment]
Well I don't object but I don't know if the issue which was causing plugin to be removed in the first place is still present, since I never fully understood the exact reason to be honest.

On the other hand of course plugin inclusion or even promise of inclusion would motivate me to work harder on plugin so if you want issues like #92 to be resolved before including the plugin I may try to accomplish fixing it in some reasonable time.

**Comment by donho** [comment]
Please solve the critical issues and let me know when you're ready. It's clear that I have to remove the critical plugin, but we can try on 1 release at least to see if there's any crash or critical issue.
